# Generated by Django 5.0 on 2024-01-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
