# Generated by Django 5.0 on 2024-01-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_room_id_alter_room_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='if_allocated',
        ),
        migrations.AddField(
            model_name='room',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='if_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
