# Generated by Django 5.0 on 2024-01-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_student_id_room_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='student',
            new_name='user',
        ),
    ]
